<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Evote360.Core\Evote360.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Mappings\" />
    <Folder Include="Services\Implementations\" />
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
